language: python
python:
  - "2.7"
install:
  - pip install -r requirements.txt
  - pip install -r django_requirements.txt
  - pip install coveralls
script:
  - coverage run -m nose
  - pep8
  - pylint -f parseable xblock
after_success:
  - coveralls
