language: python
sudo: false
python:
  - 2.7
  - 3.5
cache: pip
install:
  - pip install -r requirements/travis.txt
env:
  - TOX_ENV=django111
  - TOX_ENV=django20
  - TOX_ENV=django21
  - TOX_ENV=django22
matrix:
  exclude:
  - python: 2.7
    env: TOX_ENV=django20
  - python: 2.7
    env: TOX_ENV=django21
  - python: 2.7
    env: TOX_ENV=django22
  include:
    - python: 3.5
      env: TOX_ENV=docs
    - python: 3.5
      env: TOX_ENV=quality
script:
  - tox -e $TOX_ENV
after_success:
  - codecov
deploy:
  provider: pypi
  user: edx
  password:
    secure: GMMSN5LVnZjrolwh293uIM9oxdl7NP6ksUzuiupHuFhW6KdxL9YWmQ+XNal6uThPoShmOdjpAvjAmff2q+mp495bH8epiRt700VHw4t+3eUmdUD2Xan3dg+iX3mg6jaDRwmgALd6NAbUSI9GPffd8m3SrvmwjyHMcM+/JWpjlcY=
  distributions: sdist bdist_wheel
  on:
    tags: true
    python: 3.5
    condition: '$TOX_ENV = quality'
