language: python
sudo: false
branches:
  only:
    - master
python:
  - 2.7
  - 3.5
cache: pip
install:
  - pip install tox
  - pip install codecov
env:
  - TOX_ENV=django18
  - TOX_ENV=django110
  - TOX_ENV=django111
matrix:
  include:
    - python: 3.5
      env: TOX_ENV=docs
script:
  - tox -e $TOX_ENV
after_success:
  - codecov
deploy:
  provider: pypi
  user: edx
  password:
    secure: GMMSN5LVnZjrolwh293uIM9oxdl7NP6ksUzuiupHuFhW6KdxL9YWmQ+XNal6uThPoShmOdjpAvjAmff2q+mp495bH8epiRt700VHw4t+3eUmdUD2Xan3dg+iX3mg6jaDRwmgALd6NAbUSI9GPffd8m3SrvmwjyHMcM+/JWpjlcY=
  distributions: sdist bdist_wheel
  on:
    tags: true
    python: 3.5
